# Generated by Django 5.0.3 on 2024-03-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(editable=False, null=True, unique=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('cost', models.PositiveIntegerField(default=1, null=True)),
                ('reward', models.PositiveIntegerField(default=1, null=True)),
                ('date_created', models.DateField(null=True)),
                ('date_completed', models.DateField(null=True)),
            ],
        ),
    ]
