# Generated by Django 5.0.3 on 2024-03-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_deadqueuetaskevent_atempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
