# Generated by Django 5.0.3 on 2024-03-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_task_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='jira_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
