# Generated by Django 5.0.2 on 2024-03-15 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='uuid',
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
    ]
