# Generated by Django 5.0.2 on 2024-03-15 20:38

from django.db import migrations
from django.db import migrations
import uuid

def assign_uuid(apps, schema_editor):
    Account = apps.get_model('account', 'Account')
    for account in Account.objects.all():
        account.uuid = uuid.uuid4()
        account.save(update_fields=['uuid'])

class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_uuid'),
    ]

    operations = [
        migrations.RunPython(assign_uuid),
    ]
