# Generated by Django 5.0.3 on 2024-03-17 10:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0005_remove_payoutlog_account_remove_account_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayOutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, null=True)),
                ('amount', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to='account.account')),
            ],
        ),
    ]
