# Generated by Django 5.0.2 on 2024-03-15 20:35

from django.db import migrations

import uuid

def assign_uuid(apps, schema_editor):
    Task = apps.get_model('task', 'Task')
    for task in Task.objects.all():
        task.uuid = uuid.uuid4()
        task.save(update_fields=['uuid'])



class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_task_cost_task_reward_task_uuid'),
    ]

    operations = [
        migrations.RunPython(assign_uuid)
    ]
