# Generated by Django 5.0.2 on 2024-03-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20240315_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='task',
            name='reward',
        ),
        migrations.AddField(
            model_name='task',
            name='jira_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
