# Generated by Django 5.0.3 on 2024-03-16 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_operationlog_task_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationlog',
            name='is_processed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker', to='account.account'),
        ),
        migrations.CreateModel(
            name='PayOutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to='account.account')),
            ],
        ),
    ]
