# Generated by Django 5.0.3 on 2024-03-17 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_operationlog_is_processed_alter_operationlog_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payoutlog',
            name='account',
        ),
        migrations.DeleteModel(
            name='OperationLog',
        ),
        migrations.DeleteModel(
            name='PayOutLog',
        ),
    ]
